version: '3.7'

services:
  docker-fastapi:
      image: svo0175/stylegan
      ports:
        - "9000:9000"
      deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  docker-react:
      image: svo0175/hyperfei
      depends_on:
        - docker-fastapi
      ports:
        - "3000:3000"